### ISSUE TITLE
Create namespace bypasses reservation

### ISSUE THREAD

**Issue by dgoodwin** [openshift/kubernetes-namespace-reservation#6]
Not 100% sure if this is a problem but seems like it may be:

```
$ oc create -f artifacts/example/reserve-deads.yaml 
namespacereservation "deads" created                 
$ oc create namespace deads                         
namespace "deads" created                            
$ oc new-project deads                              
Error from server (Forbidden): "deads" is reserved   
```

**Comment by deads2k** [comment]
If you want to update it, the rules are expressed here: https://github.com/openshift/kubernetes-namespace-reservation/blob/master/artifacts/install/apiserver-template.yaml#L101-L122

**Comment by dgoodwin** [comment]
Perfect thanks, we will figure out what to do with that in future.
